### ISSUE TITLE
Document licensing terms for source APIs

### ISSUE THREAD

**Issue by jpmckinney** [influencemapping/whos_got_dirt-server#12]
So that consumers can easily refer to this in one place, and not have to chase down the docs for each API. Not sure what the license is on the following (or if the data is even licensed):
- [QuienManda](https://github.com/civio/quienmanda.es/wiki/Qui%C3%A9n-Manda-API)
- [a HÁLÓ](http://ahalo.hu/front/api)
- [WhoDoTheyServe](http://www.whodotheyserve.com/#/doc/about)

**Comment by miguelpaz** [comment]
@jpmckinney what are you looking for? Poderopedia`s terms of service for content are under Creative Commons 3.0 under the following conditions:
-You can copy, distribute and transmit the content of Poderopedia.
-You can not edit the contents, except to reflect changes relative to time, place and editorial style.
-You are not allowed to sell the contents of Poderopedia
-You can publish Poderopedia content on a website that includes commercial ads but can not include ads that have been sold specifically around our content.
-If Poderopedia contents are published, they must be linked to the URLs of content originally published in Poderopedia. It should be credited as: Author: "Poderopedia" or Via Poderopedia or Powered by Poderopedia
-You can not republish contents Poderopedia automatically: you must select the contents you want republished individually. On the API level, there is a specific amount of API requests TBD yet. Any thoughts on that?
-The website is owned Poderopedia.org Poderomedia Foundation and its use is free to anywhere in the world under the GNU General Public Licence (GPL) version 3. This means that if changes are made or distributed must be made available to the same open source license. Poderopedia documentation Ontology and are also available under the same GNU GPL Version 3.
-Poderopedia.org design is owned by Poderomedia Foundation.
Link to this information (in spanish)
http://www.poderopedia.org/poderopedia/pages/index/20

**Comment by jpmckinney** [comment]
@miguelpaz The "Términos y condiciones de uso" link http://www.poderopedia.org/acercade/condiciones_de_uso is broken on http://api.poderopedia.org/

**Comment by jpmckinney** [comment]
There is no single CC 3.0 license. As far as I can tell, the license terms describe [CC-BY-NC-ND 3.0](https://creativecommons.org/licenses/by-nc-nd/3.0/). It's unusual to state that the license is CC, but to then list a whole set of possibly conflicting terms. It's better to just let CC describe the terms.

**Comment by jpmckinney** [comment]
Added to wiki: https://github.com/influencemapping/whos_got_dirt-server/wiki
