### ISSUE TITLE
Add API keys

### ISSUE THREAD

**Issue by jpmckinney** [influencemapping/whos_got_dirt-server#6]
Add `key` field at same level as `query`.

ref. https://developers.google.com/freebase/v1/mql-overview

**Comment by CountCulture** [comment]
Seems like a good idea

**Comment by jpmckinney** [comment]
Instead of having a `key` field at the same level as `query` as in MQL, whose value would be a hash of keys (which would be different from how MQL does it anyhow, as it supports only a single key), we'll instead put the keys in the same part of the `queries` object as the list of APIs to query in #3.

**Comment by jpmckinney** [comment]
Actually - I'll just leave the API keys in `query` as currently documented. Moving them around doesn't avoid any repetition as you need to state the endpoints (with API keys) to query for each `query`. The only option to avoid repetition would be to put the API keys at the envelope level, with each `query` just stating the APIs to query, but that's more complex and thus more likely to cause confusion/errors.
